export const alertConstants = {
    SUCCESS: 'ALERT_SUCCESS',
    ERROR: 'ALERT_ERROR',
    CLEAR: 'ALERT_CLEAR'
};

export const ideasConstants = {
    GET_ALL_REQUEST: 'IDEAS_GET_ALL_REQUEST',
    GET_ALL_SUCCESS: 'IDEAS_GET_ALL_SUCCESS',
    GET_ALL_FAILURE: 'IDEAS_GET_ALL_FAILURE',
    SET_NEW_IDEA_BOOLEAN_TO_TRUE: 'SET_NEW_IDEA_BOOLEAN_TO_TRUE'
};

export const boardConstants = {
    GET_REQUEST: 'BOARD_GET_REQUEST',
    GET_SUCCESS: 'BOARD_GET_SUCCESS',
    GET_FAILURE: 'BOARS_GET_FAILURE',
};

export const carouselConstants = {
    GET_REQUEST: 'CAROUSEL_GET_REQUEST',
    GET_SUCCESS: 'CAROUSEL_GET_SUCCESS',
    GET_FAILURE: 'CAROUSEL_GET_FAILURE',
};

