export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    GET_ALL_REQUEST: 'USERS_GET_ALL_REQUEST',
    GET_ALL_SUCCESS: 'USERS_GET_ALL_SUCCESS',
    GET_ALL_FAILURE: 'USERS_GET_ALL_FAILURE',

    DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    DELETE_FAILURE: 'USERS_DELETE_FAILURE',

    GETIDEASPERUSER_REQUEST: 'USERS_GETIDEASPERUSER_REQUEST',
    GETIDEASPERUSER_SUCCESS: 'USERS_GETIDEASPERUSER_SUCCESS',
    GETIDEASPERUSER_FAILURE: 'USERS_GETIDEASPERUSER_FAILURE',

    PASSWORD_CHANGED_AT_LOGIN: 'PASSWORD_HAS_BEEN_CHANGED_AT_LOGIN',
    USERNAME_CHANGED_AT_LOGIN: 'USERNAME_HAS_BEEN_CHANGED_AT_LOGIN',
    REMEMBER_ME_CHANGED_AT_LOGIN: 'REMEMBER_ME_HAS_BEEN_CHANGED_AT_LOGIN',

    GET_REQUEST: 'USERS_GET_REQUEST',
    GET_SUCCESS: 'USERS_GET_SUCCESS',
    GET_FAILURE: 'USERS_GET_FAILURE',

    CONFIRM_SUCCESSFUL_LOGIN_AT_NOTIFICATION_ON_CONTENT_PAGE: 'CONFIRM_SUCCESSFUL_LOGIN_AT_NOTIFICATION_ON_CONTENT_PAGE',

    SAVE_CURRENT_USER: 'SAVE_CURRENT_USER'
};

export const alertConstants = {
    SUCCESS: 'ALERT_SUCCESS',
    ERROR: 'ALERT_ERROR',
    CLEAR: 'ALERT_CLEAR'
};

export const ideasConstants = {
    GET_ALL_REQUEST: 'IDEAS_GET_ALL_REQUEST',
    GET_ALL_SUCCESS: 'IDEAS_GET_ALL_SUCCESS',
    GET_ALL_FAILURE: 'IDEAS_GET_ALL_FAILURE',
    SET_NEW_IDEA_BOOLEAN_TO_TRUE: 'SET_NEW_IDEA_BOOLEAN_TO_TRUE',
};

export const currentIdeasConstants = {
    GET_ALLCURRENT_SUCCESS: 'USERS_GET_ALLCURRENT_SUCCESS',
    SAVE_SEARCH_TEXT: 'SAVE_SEARCH_TEXT'
};//

export const ideaConstants = {
    GET_REQUEST: 'IDEA_GET_REQUEST',
    GET_SUCCESS: 'IDEA_GET_SUCCESS',
    GET_FAILURE: 'IDEA_GET_FAILURE',
    POST_REQUEST: 'IDEA_POST_REQUEST',
    POST_SUCCESS: 'IDEA_POST_SUCCESS',
    POST_FAILURE: 'IDEA_POST_FAILURE',
    SAVE_CURRENT_IDEA: 'SAVE_CURRENT_IDEA'
};

export const upvoteConstants = {
    POST_REQUEST: 'UPVOTE_POST_REQUEST',
    POST_SUCCESS: 'UPVOTE_POST_SUCCESS',
    POST_FAILURE: 'UPVOTE_POST_FAILURE',
};

export const fingerprintConstants = {
    POST_REQUEST: 'FINGERPRINT_POST_REQUEST',
    POST_SUCCESS: 'FINGERPRINT_POST_SUCCESS',
    POST_FAILURE: 'FINGERPRINT_POST_FAILURE',
};

export const commentsConstants = {
    GET_ALL_REQUEST: 'COMMENTS_GET_ALL_REQUEST',
    GET_ALL_SUCCESS: 'COMMENTS_GET_ALL_SUCCESS',
    GET_ALL_FAILURE: 'COMMENTS_GET_ALL_FAILURE',
};

export const commentConstants = {
    POST_REQUEST: 'COMMENT_POST_REQUEST',
    POST_SUCCESS: 'COMMENT_POST_SUCCESS',
    POST_FAILURE: 'COMMENT_POST_FAILURE',
};

export const boardConstants = {
    GET_REQUEST: 'BOARD_GET_REQUEST',
    GET_SUCCESS: 'BOARD_GET_SUCCESS',
    GET_FAILURE: 'BOARS_GET_FAILURE',
};

export const paginationConstants = {
    PAGE_NEXT: 'PAGE_NEXT',
    PAGE_PREVIOUS: 'PAGE_PREVIOUS',
    PAGE_RESET: 'PAGE_RESET',
    PAGE_SLICE: 'PAGE_SLICE',
    PAGE_SET_LAST: 'PAGE_SET_LAST'
};
